<tr><td class="left">Дата осмотра</td><td class="field">
<?php
print ('<input class="numfield" type="text" id="Date1" name="Date1" value="'.$values['Date1'].'" size="5" onchange="CalcAge();doHighlight(\'Date1\')"/>/');
print ('<input class="numfield" type="text" id="Date2" name="Date2" value="'.$values['Date2'].'" size="5" onchange="CalcAge();doHighlight(\'Date2\')"/>/');
print ('<input class="numfield" type="text" id="Date3" name="Date3" value="'.$values['Date3'].'" size="5" onchange="CalcAge();doHighlight(\'Date3\')"/></td><td></td></tr>');
?>